### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by natraj-s** [kmatchu/Language-Learner#12]
- [x] Hangman created and functional
- [x] Wordsearch created and functional
- [x] Jumble created and functional
